version: '2'

services:
  web:
    image: web
    build: web/
    container_name: web
    ports:
      - "666:80"
    volumes:
      - ./src:/var/www/html
    links:
      - db
      - php
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: root
       MYSQL_ROOT_PASSWORD: imfkingenius
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #    - PMA_ARBITRARY=1
  #    - PMA_HOST=db
  #    - PMA_USER=root
  #    - PMA_PASSWORD=0987237533
  #   ports:
  #    - 8080:80
  #   volumes:
  #    - /sessions
  redis:
    image: redis:latest
    container_name: redis
    ports:
       - "6379:6379"
  php:
    image: php:7-fpm
    volumes:
      - ./src:/var/www/html