version: '3'

services:
  web:
    image: web
    build:
      context: web/
      args:
        TIMEZONE: Asia/Taipei
    container_name: web
    ports:
      - "666:80"
    volumes:
      - ./src:/var/www/html
    links:
      # - db
      - php
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: root
       MYSQL_ROOT_PASSWORD: 
  redis:
    image: redis:latest
    container_name: redis
    ports:
       - "6379:6379"
  php:
    image: php
    build:
      context: php/
      args:
        TIMEZONE: Asia/Taipei
    volumes:
      - ./src:/var/www/html
      - ./logs/symfony:/var/www/symfony/app/logs
    # links:
    #   - db
